import 'package:world_time/worldTimeApi.dart';

List location() {

  List locations;
  
    return  locations = [
    WorldTimeApi(url: "Africa/Abidjan", location: "Abidjan", flag: ""),
    WorldTimeApi(url: "Africa/Accra", location: "Accra", flag: ""),
    WorldTimeApi(url: "Africa/Algiers", location: "Algiers", flag: ""),
    WorldTimeApi(url: "Africa/Bissau", location: "Bissau", flag: ""),
    WorldTimeApi(url: "Africa/Cairo", location: "Cairo", flag: ""),
    WorldTimeApi(url: "Africa/Casablanca", location: "Casablanca", flag: ""),
    WorldTimeApi(url: "Africa/Ceuta", location: "Ceuta", flag: ""),
    WorldTimeApi(url: "Africa/El_Aaiun", location: "El_Aaiun", flag: ""),
    WorldTimeApi(
        url: "Africa/johannesburg", location: "johannesburg", flag: ""),
    WorldTimeApi(url: "Africa/juba", location: "juba", flag: ""),
    WorldTimeApi(url: "Africa/khartoum", location: "khartoum", flag: ""),
    WorldTimeApi(url: "Africa/Lagos", location: "Lagos", flag: ""),
    WorldTimeApi(url: "Africa/Maputo", location: "Maputo", flag: ""),
    WorldTimeApi(url: "Africa/Monrovia", location: "Monrovia", flag: ""),
    WorldTimeApi(url: "Africa/Nairobi", location: "Nairobi", flag: ""),
    WorldTimeApi(url: "Africa/Ndjamena", location: "Ndjemena", flag: ""),
    WorldTimeApi(url: "Africa/Sao_Tome", location: "Sao_Tome", flag: ""),
    WorldTimeApi(url: "Africa/Tripoli", location: "Tripoli", flag: ""),
    WorldTimeApi(url: "Africa/Tunis", location: "Tunis", flag: ""),
    WorldTimeApi(url: "Africa/Windhoek", location: "Windhoek", flag: ""),
    WorldTimeApi(url: "Africa/Adak", location: "Adak", flag: ""),
    WorldTimeApi(url: "America/Anchorage", location: "Anchorage", flag: ""),
    WorldTimeApi(url: "America/Araguaina", location: "Araguaina", flag: ""),
    WorldTimeApi(
        url: "America/Argentina/Buenos_Aires",
        location: "Argentina/Buenos_Aires",
        flag: ""),
    WorldTimeApi(url: "America/Asuncion", location: "Asuncion", flag: ""),
    WorldTimeApi(url: "America/Atikokan", location: "Atikokan", flag: ""),
    WorldTimeApi(url: "America/Bahia", location: "Bahia", flag: ""),
    WorldTimeApi(url: "America/Barbados", location: "Barbados", flag: ""),
    WorldTimeApi(url: "America/Belem", location: "Belem", flag: ""),
    WorldTimeApi(url: "America/Belize", location: "Belize", flag: ""),
    WorldTimeApi(
        url: "America/Blanc-Sablon", location: "Blanc-Sablon", flag: ""),
    WorldTimeApi(url: "America/Boa_Vista", location: "Boa_Vista", flag: ""),
    WorldTimeApi(url: "America/Bogota", location: "Bogota", flag: ""),
    WorldTimeApi(url: "America/Boise", location: "Boise", flag: ""),
    WorldTimeApi(
        url: "America/Cambridge_Bay", location: "Cambridge_Bay", flag: ""),
    WorldTimeApi(
        url: "America/Campo_Grande", location: "Campo_Grande", flag: ""),
    WorldTimeApi(url: "America/Cancum", location: "Cancum", flag: ""),
    WorldTimeApi(url: "America/Caracas", location: "Caracas", flag: ""),
    WorldTimeApi(url: "America/Cayenne", location: "Cayenne", flag: ""),
    WorldTimeApi(url: "America/Chicago", location: "Chicago", flag: ""),
    WorldTimeApi(url: "America/Chihuahua", location: "Chihuahua", flag: ""),
    WorldTimeApi(url: "America/Costa_Rica", location: "Costa_Rica", flag: ""),
    WorldTimeApi(url: "America/Creston", location: "Creston", flag: ""),
    WorldTimeApi(url: "America/Cuiaba", location: "Cuiaba", flag: ""),
    WorldTimeApi(url: "America/Curacao", location: "Curacao", flag: ""),
    WorldTimeApi(
        url: "America/Danmarkshavn", location: "Danmarkshavn", flag: ""),
    WorldTimeApi(url: "America/Dawson", location: "Dawson", flag: ""),
    WorldTimeApi(
        url: "America/Dawson_Creek", location: "Dawson_Creek", flag: ""),
    WorldTimeApi(url: "America/Denver", location: "Denver", flag: ""),
    WorldTimeApi(url: "America/Detroit", location: "Detroit", flag: ""),
    WorldTimeApi(url: "America/Edmonton", location: "Edmonton", flag: ""),
    WorldTimeApi(url: "America/Eirunepe", location: "Eirunepe", flag: ""),
    WorldTimeApi(url: "America/El_Salvador", location: "El_Salvador", flag: ""),
    WorldTimeApi(url: "America/Fort_Nelson", location: "Fort_Nelson", flag: ""),
    WorldTimeApi(url: "America/Fortaleza", location: "Fortaleza", flag: ""),
    WorldTimeApi(url: "America/Glace_Bay", location: "Glace_Bay", flag: ""),
    WorldTimeApi(url: "America/Grand_Turk", location: "Grand_Turk", flag: ""),
    WorldTimeApi(url: "America/Guayaquil", location: "Guayaquil", flag: ""),
    WorldTimeApi(url: "America/Guyana", location: "Guyana", flag: ""),
    WorldTimeApi(url: "America/Halifix", location: "Halifix", flag: ""),
    WorldTimeApi(url: "America/Havana", location: "Havana", flag: ""),
    WorldTimeApi(url: "America/Hermosillo", location: "Hermosillo", flag: ""),
    WorldTimeApi(url: "America/Inuvik", location: "Inuvik", flag: ""),
    WorldTimeApi(url: "America/Iqaluit", location: "Iqaluit", flag: ""),
    WorldTimeApi(url: "America/Jamaica", location: "Jamaica", flag: ""),
    WorldTimeApi(url: "America/Juneau", location: "Juneau", flag: ""),
    WorldTimeApi(url: "America/La_Paz", location: "La_Paz", flag: ""),
    WorldTimeApi(url: "America/Lima", location: "Lima", flag: ""),
    WorldTimeApi(url: "America/Los_Angeles", location: "Los_Angeles", flag: ""),
    WorldTimeApi(url: "America/Maceio", location: "Maceio", flag: ""),
    WorldTimeApi(url: "America/Managua", location: "Managua", flag: ""),
    WorldTimeApi(url: "America/Manaus", location: "Manaus", flag: ""),
    WorldTimeApi(url: "America/Martinique", location: "Martinique", flag: ""),
    WorldTimeApi(url: "America/Matamoros", location: "Matamoros", flag: ""),
    WorldTimeApi(url: "America/Mazatlan", location: "Mazatlan", flag: ""),
    WorldTimeApi(url: "America/Menominee", location: "Menominee", flag: ""),
    WorldTimeApi(url: "America/Merida", location: "Merida", flag: ""),
    WorldTimeApi(url: "America/Metlakatla", location: "Metlakatla", flag: ""),
    WorldTimeApi(url: "America/Mexico_City", location: "Mexico_City", flag: ""),
    WorldTimeApi(url: "America/Miquelon", location: "Miquelon", flag: ""),
    WorldTimeApi(url: "America/Moncton", location: "Moncton", flag: ""),
    WorldTimeApi(url: "America/Monterrey", location: "Monterrey", flag: ""),
    WorldTimeApi(url: "America/Montevideo", location: "Montevideo", flag: ""),
    WorldTimeApi(url: "America/Nassau", location: "Nassau", flag: ""),
    WorldTimeApi(url: "America/New_York", location: "New_York", flag: ""),
    WorldTimeApi(url: "America/Nipigon", location: "Nipigon", flag: ""),
    WorldTimeApi(url: "America/Nome", location: "Nome", flag: ""),
    WorldTimeApi(url: "America/Noronha", location: "Noronha", flag: ""),
    WorldTimeApi(url: "America/Nuuk", location: "Nuuk", flag: ""),
    WorldTimeApi(url: "America/Ojinaga", location: "Ojinaga", flag: ""),
    WorldTimeApi(url: "America/Panama", location: "Panama", flag: ""),
    WorldTimeApi(url: "America/Pangnirtung", location: "Pangnirtung", flag: ""),
    WorldTimeApi(url: "America/Paramaribo", location: "Paramaribo", flag: ""),
    WorldTimeApi(url: "America/Phoenix", location: "Phoenix", flag: ""),
    WorldTimeApi(
        url: "America/Port-au-Prince", location: "Port-au-Prince", flag: ""),
    WorldTimeApi(
        url: "America/Port_of_Spain", location: "Port_of_Spain", flag: ""),
    WorldTimeApi(url: "America/Porto_Velho", location: "Porto_Velho", flag: ""),
    WorldTimeApi(url: "America/Puerto_Rico", location: "Puerto_Rico", flag: ""),
    WorldTimeApi(
        url: "America/Punta_Arenas", location: "Punta_Arenas", flag: ""),
    WorldTimeApi(url: "America/Rainy_River", location: "Rainy_River", flag: ""),
    WorldTimeApi(
        url: "America/Rankin_Inlet", location: "Rankin_Inlet", flag: ""),
    WorldTimeApi(url: "America/Recife", location: "Recife", flag: ""),
    WorldTimeApi(url: "America/Regina", location: "Regina", flag: ""),
    WorldTimeApi(url: "America/Resolute", location: "Resolute", flag: ""),
    WorldTimeApi(url: "America/Rio_Branco", location: "Rio_Branco", flag: ""),
    WorldTimeApi(url: "America/Santarem", location: "Santerem", flag: ""),
    WorldTimeApi(url: "America/Santiago", location: "Santiago", flag: ""),
    WorldTimeApi(
        url: "America/Santo_Domingo", location: "Santo_Domingo", flag: ""),
    WorldTimeApi(url: "America/Sao_Paulo", location: "Sao_Paulo", flag: ""),
    WorldTimeApi(
        url: "America/Scoresbysund", location: "Scoresysund", flag: ""),
    WorldTimeApi(url: "America/Sitka", location: "Sitka", flag: ""),
    WorldTimeApi(url: "America/St_Johns", location: "St_Johns", flag: ""),
    WorldTimeApi(
        url: "America/Swift_Current", location: "Swift_Current", flag: ""),
    WorldTimeApi(url: "America/Tegucigalpa", location: "Tegucigalpa", flag: ""),
    WorldTimeApi(url: "America/Thule", location: "Thule", flag: ""),
    WorldTimeApi(url: "America/Thunder_Bay", location: "Thunder_Bay", flag: ""),
    WorldTimeApi(url: "America/Tijuana", location: "Tijuana", flag: ""),
    WorldTimeApi(url: "America/Toronto", location: "Toronto", flag: ""),
    WorldTimeApi(url: "America/Vancouver", location: "Vancouver", flag: ""),
    WorldTimeApi(url: "America/Whitehorse", location: "Whitehorse", flag: ""),
    WorldTimeApi(url: "America/Winnipeg", location: "Winnipeg", flag: ""),
    WorldTimeApi(url: "America/Yakutat", location: "Yakutat", flag: ""),
    WorldTimeApi(url: "America/Yellowknife", location: "Yellowknife", flag: ""),
    WorldTimeApi(url: "Asia/Amman", location: "Amman", flag: ""),
    WorldTimeApi(url: "Asia/Almaty", location: "Almaty", flag: ""),
    WorldTimeApi(url: "Asia/Anadyr", location: "Anadyr", flag: ""),
    WorldTimeApi(url: "Asia/Aqtau", location: "Aqtau", flag: ""),
    WorldTimeApi(url: "Asia/Aqtobe", location: "Aqtobe", flag: ""),
    WorldTimeApi(url: "Asia/Ashgabat", location: "Ashgabat", flag: ""),
    WorldTimeApi(url: "Asia/Atyrau", location: "Atyrau", flag: ""),
    WorldTimeApi(url: "Asia/Baghdad", location: "Baghdad", flag: ""),
    WorldTimeApi(url: "Asia/Baku", location: "Baku", flag: ""),
    WorldTimeApi(url: "Asia/Bangkok", location: "Bangkok", flag: ""),
    WorldTimeApi(url: "Asia/Barnaul", location: "Barnaul", flag: ""),
    WorldTimeApi(url: "Asia/Beirut", location: "Beirut", flag: ""),
    WorldTimeApi(url: "Asia/Bishkek", location: "Bishkek", flag: ""),
    WorldTimeApi(url: "Asia/Brunei", location: "Brunei", flag: ""),
    WorldTimeApi(url: "Asia/Chita", location: "Chita", flag: ""),
    WorldTimeApi(url: "Asia/Choibalsan", location: "Choibalsan", flag: ""),
    WorldTimeApi(url: "Asia/Colombo", location: "Colombo", flag: ""),
    WorldTimeApi(url: "Asia/Damascus", location: "Damascus", flag: ""),
    WorldTimeApi(url: "Asia/Dhaka", location: "Dhaka", flag: ""),
    WorldTimeApi(url: "Asia/Dili", location: "Dili", flag: ""),
    WorldTimeApi(url: "Asia/Dubai", location: "Dubai", flag: ""),
    WorldTimeApi(url: "Asia/Dushande", location: "Dushande", flag: ""),
    WorldTimeApi(url: "Asia/Famagusta", location: "Famagusta", flag: ""),
    WorldTimeApi(url: "Asia/Gaza", location: "Gaza", flag: ""),
    WorldTimeApi(url: "Asia/Hebron", location: "Hebron", flag: ""),
    WorldTimeApi(url: "Asia/Ho_Chi_Minh", location: "Ho_Chi_Minh", flag: ""),
    WorldTimeApi(url: "Asia/Hong_kong", location: "Hong_kong", flag: ""),
    WorldTimeApi(url: "Asia/Hovd", location: "Hovd", flag: ""),
    WorldTimeApi(url: "Asia/Irkutsk", location: "Irkutsk", flag: ""),
    WorldTimeApi(url: "Asia/Jakarta", location: "Jakarta", flag: ""),
    WorldTimeApi(url: "Asia/Jayapura", location: "Jayapura", flag: ""),
    WorldTimeApi(url: "Asia/Jerusalem", location: "Jerusalem", flag: ""),
    WorldTimeApi(url: "Asia/Kabul", location: "Kabul", flag: ""),
    WorldTimeApi(url: "Asia/Kamchatka", location: "Kamchatka", flag: ""),
  ];
}
